name: Deploy to InfinityFree via FTP

on:
  push:
    branches: [ main ]

jobs:
  web-deploy:
    name: Deploy to InfinityFree
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        fetch-depth: 2

    - name: Sync files to InfinityFree FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ftpupload.net
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: /htdocs/
        exclude: |
          **/.git*
          **/.git*/**
          **/.vscode/**
          **/README.md
          **/screenshots/**
